<?php
/**
 * @file
 * Code for the Access Incident feature.
 */

include_once 'acc_incidents.features.inc';
/**
 * Implements hook_og_features_registry()
 */
function acc_incidents_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'acc_incidents';
  $feature->name = t('Access Incidents');
  $feature->description = t('Humanitarian Access Incidents Content Type, Views, Context, Search Index, Facets, Map');
  $feature->components = array(
    'node' => array(
      'acc_incident',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_og_features_toggle($entity, $entity_id, $entity_type, $features)
 */
function acc_incidents_og_features_toggle($entity, $entity_id, $entity_type, $features) {
  if (isset($features['acc_incident'])) {
    $mlid = og_menu_single_get_link_mlid('node', $entity_id);
    if (empty($features['acc_incident'])) {
      menu_link_delete(NULL, 'node/'.$entity_id.'/access/incidents');
    }
    else {
      // See if menu link already exists
      $menu_link = menu_link_get_preferred('node/'.$entity_id.'/access/incidents', OG_MENU_SINGLE_MENU_NAME);
      if (empty($menu_link)) {
        $menu_link = array(
          'link_path' => 'node/'.$entity_id.'/access/incidents',
          'link_title' => 'Access Incidents',
          'menu_name' => OG_MENU_SINGLE_MENU_NAME,
          'weight' => 99,
          'plid' => $mlid,
        );
        menu_link_save($menu_link);
      }
    }
  }

}
